---
title: "Figure 1 map"
author: "j"
date: "7/16/2018"
output: html_document
---
```{r}
library(tidyverse)
library(rnaturalearth)
library(cowplot)
```



#America
```{r}
mex <- ne_countries(continent = c("north america", "south america"), scale = "medium", returnclass = "sf")
ls <- ggplot(data = mex) +
  geom_sf()

ls

```


```{r}
ls <- ls +
  lims(x = c(-120, -60))
ls
```


```{r}
ls <- ls +
  lims(x = c(-120, -60))
ls
```




##Reference:Baja Peninsula

```{r}
baja <- ggplot() +
    geom_sf(data = mex) +
  
   lims(x = c(-117, -109), y = c(22, 32.5)) + 
  
    geom_point(aes(x = -115.171839, y = 27.871624), shape = 22, size = 4, color = "red") 

baja
```


#progress

```{r}
ggplot() +
    geom_sf(data = mex) +
  
  lims(x = c(-116, -114), y = c(27, 29)) +
   geom_point(aes(x = -115, y = 28), shape = 22, size = 4) 
    


```

#better zoomed in version (square)

```{r}


 ggplot() +
    geom_sf(data = mex) +
  
  lims(x = c(-116, -114), y = c(27, 29)) +
   geom_point(aes(x = -115.171839, y = 27.871624), shape = 22, size = 4) 
    

```







#mexico
```{r}
site <- ne_countries(country = "mexico", returnclass = "sf", scale = "large")
site

ggplot() +
  geom_sf(data= site) +
  geom_point(aes(x = -115.171839, y = 27.871624), shape = 22, size = 10, color = "red")
  


```



```{r}
baja
```


##regional.final

```{r}
#22 is square 18 is diamond
regional <- ggplot() +
    geom_sf(data = mex) +
  
  lims(x = c(-116, -114), y = c(27, 29)) +
   geom_point(aes(x = -115.171839, y = 27.871624), shape = 18, size = 2, 
   color = "blue")+
   geom_point(aes(x = -115.171839, y = 27.871624), shape = 22, size = 4) 
   regional
```

