---
title: "building Population growth model"
author: "j"
date: "7/2/2018"
output: html_document
---

the model is: 


$$N_{t + 1} = N_t + rN_t(1 - \frac{N_t}{K})$$

#Parameters

```{r}
r <- 0.5
K <- 100
N0 <- 10
nsteps <- 20
```


```{r}
# define a vector of time and N
time <- c(0:nsteps)
N <- numeric(length = length(time))

#Assign initial population size

N[1] <- N0


for (t in 1:nsteps) {
  N[t + 1] <- N[t] + (r * N[t] * (1 - (N[t] / K)))
  plot(N)
}

# end for loop

#create data frame with sim results

simul <- data.frame(time, N)
```



```{r}
library(tidyverse)
```





```{r}
ggplot(data = simul, mapping = aes(x = time, y = N)) +
 # geom_line() +
  geom_point(color = "steelblue", size = 2) +
  geom_line() +
  theme_bw()
```



# create a function


```{r}

my_fun <- function(a, b){
  c <- a+b
  return(c)
  
}

```



```{r}
my_fun(a = 2, b =3)
```































#create growth model function
$$N_{t + 1} = N_t + rN_t(1 - \frac{N_t}{K})$$

```{r}

logistic_model <- function(r = 1, K = 100, N0 = 10, nsteps = 50, c = 0.5, p = 10){

  # define a vector of time and N THIS IS ODD
  time <- c(0:nsteps)
  N <- numeric(length = length(time))

  #Assign initial population size
  
  N[1] <- N0

  for (t in 1:nsteps) {
    N[t + 1] <- N[t] + (r * N[t] * (1 - (N[t] / K))) - c * N[t]
  }
  # end for loop
  
  #create data frame with sim results
  
  simul <- data.frame(time, N) %>% 
    mutate(C = c * N,
           R = p*C)
  
  
  return(simul)
}

```







```{r}
results <- logistic_model()

ggplot(data = results, mapping = aes(x = time, y = N)) +
 # geom_line() +
  geom_point(color = "steelblue", size = 2) +
  geom_line() +
  theme_bw()



```







```{r}
logistic_model(c = 0.25, N0 = 5, r = 1) %>% 
  gather(variable, value, -time) %>% 
   ggplot(mapping = aes(x = time, y = value)) +
 # geom_line() +
  geom_point(color = "steelblue", size = 2) +
  geom_line() +
  theme_bw() +
  facet_wrap( ~ variable, ncol = 2, scales = "free")
```





