---
title: "Population growth model"
author: "j"
date: "7/2/2018"
output: html_document
 
   
     
       
         
           # html_document:
      #code_folding: hide
      #toc_float: yes
      #toc : yes
---







#growth model function

$$N_{t + 1} = N_t + rN_t(1 - \frac{N_t}{K}) - cN_t$$    
 










```{r}

logistic_model <- function(r = 1, K = 100, N0 = 10, nsteps = 50, c = 0.5, p = 10){

  # define a vector of time and N THIS IS ODD
  time <- c(0:nsteps)
  N <- numeric(length = length(time))

  #Assign initial population size
  
  N[1] <- N0

  for (t in 1:nsteps) {
    N[t + 1] <- N[t] + (r * N[t] * (1 - (N[t] / K))) - c * N[t]
  }
  # end for loop
  
  #create data frame with sim results
  
  simul <- data.frame(time, N) %>% 
    mutate(C = c * N,
           R = p*C)
  
  
  return(simul)
}

```

```{r}
results <- logistic_model()

ggplot(data = results, mapping = aes(x = time, y = N)) +
 # geom_line() +
  geom_point(color = "steelblue", size = 2) +
  geom_line() +
  theme_bw()



```

```{r}
logistic_model(c = 0.25, N0 = 5, r = 1,) %>% 
  gather(variable, value, -time) %>% 
   ggplot(mapping = aes(x = time, y = value)) +
 # geom_line() +
  geom_point(color = "steelblue", size = 2) +
  geom_line() +
  theme_bw() +
  facet_wrap( ~ variable, ncol = 2, scales = "free")
```





```{r}
logistic_model(r = 1, K = 100, N0 = 10, nsteps = 50, c = 0.5, p = 10) %>% 
  ggplot(aes(x = time, y = N, color = C, size = R)) +
  geom_point()
```

logistic_model()


